version: "3.8"

services:
  native_ts:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: native_ts
    stdin_open: true
    restart: unless-stopped
    volumes:
      -  ../../simple_practices:/app
